name: Deploy to VPS

on:
  push:
    branches:
      - main  # Adjust to your main branch name  doink

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      run: |
        ssh -p 1729 -i ${{ secrets.SSHKEY }} ~/.ssh/github eve@89.147.108.14 'cd /var/www/dev-stjp && git pull origin main'
      
